---

node_version: 20

# The base directory relative to which user specific configuration files should be stored
config_dir: "{{ ansible_env.XDG_CONFIG_HOME | default(default_xdg_config_home) }}"
neovim_config_dir: "{{ config_dir }}/nvim"

python_required_packages:
  - software-properties-common
  - python3-dev
  - python3-pip

neovim_required_packages:
  - ripgrep
  - lua5.1
  - luarocks
  - neovim

pip3_name: pip3
