---

# The specific package name used to install neovim
neovim_name: neovim
neovim_ppa: ppa:neovim-ppa/unstable

# The base directory relative to which user specific configuration files should be stored
config_dir: "{{ ansible_env.XDG_CONFIG_HOME | default(default_xdg_config_home) }}"
neovim_config_dir: "{{ config_dir }}/nvim"

python_required_packages:
  - software-properties-common
  - python3-dev
  - python3-pip

neovim_required_packages:
  - ripgrep

pip3_name: pip3
