---
- hosts: localhost
  gather_facts: yes
  vars:
    - shell_profile: .zshrc
    - local_user_home: "{{ ansible_env.HOME }}" 

  pre_tasks:
    - name: Make sure 'PATH=$PATH:/home/$USER/.local/bin' is added to the shell profile
      lineinfile:
        path: "{{ local_user_home }}/{{ shell_profile }}"
        line: "export PATH=$PATH:/home/$USER/.local/bin"
        create: yes

    - name: Install Ansible tools
      pip:
        name: "{{ item }}"
      with_items:
        - yamllint
        - ansible-lint
        - molecule

    - block:
      - name: Install linux tools
        apt:
          name: "{{ item }}"
          state: present
        with_items:
          - ripgrep
          - fzf

      become: true
      become_user: root

  roles:
    - tmux

  post_tasks:
    - name: Tmux post config
      import_tasks: tmux-config.yml

