---
- hosts: localhost
  gather_facts: true
  vars:
    - shell_profile: .zshrc
    - local_user_home: "{{ lookup('env', 'HOME') }}"

  pre_tasks:
    - name: Make sure 'PATH=$PATH:/home/$USER/.local/bin'
            is added to the shell profile
      lineinfile:
        path: "{{ local_user_home }}/{{ shell_profile }}"
        line: "export PATH=$PATH:/home/$USER/.local/bin"
        create: true
        mode: u+rw

    - name: Install Ansible tools with pip
      pip:
        name: "{{ item }}"
      with_items:
        - yamllint
        - ansible-lint
        - molecule

    - name: Install packages
      block:
        - name: Install linux tools
          apt:
            name: "{{ item }}"
            state: present
          with_items:
            - ripgrep
            - fzf

      become: true
      become_user: root

  roles:
    - name: remote
      tags: remote
    - name: fonts
      tags: fonts
    - name: tmux
      tags: tmux
    - name: i3
      tags: i3
    - name: neovim
      tags: neovim

  post_tasks:
    - name: Tmux post config
      import_tasks: tmux-config.yml
