---
- name: Copy tmux .dotfiles
  copy:
    dest: "{{ local_user_home }}/.dotfiles/"
    src: files/.dotfiles/tmux

- name: Make tmux-cht.sh executable
  file:
    path: "{{ local_user_home }}/.dotfiles/tmux/tmux-cht.sh"
    mode: u+x

- name: Set bind key for cht.sh in tmux
  lineinfile:
    path: "{{ local_user_home }}/.tmux.conf"
    line: 'bind-key -r i run-shell "tmux neww {{ local_user_home }}/.dotfiles/tmux/tmux-cht.sh"'
    insertafter: "# { bind-key }"
    state: present
