---
- name: Install and configure xrdp
  block:
    
    - name: Install linux packages
      apt:
        name: xrdp 
        state: present
        update_cache: true

    - name: Configure Globals xrdp port
      community.general.ini_file:
        path: /etc/xrdp/xrdp.ini
        section: Globals
        option: port
        value: "{{ xrdp_globals_port }}"
        state: present

    - name: Configure Globals max_bpp
      community.general.ini_file:
        path: /etc/xrdp/xrdp.ini
        section: Globals
        option: max_bpp
        value: "{{ xrdp_globals_max_bpp }}"
        state: present

    - name: Configure Xvnc xserverbpp
      community.general.ini_file:
        path: /etc/xrdp/xrdp.ini
        section: Xvnc
        option: xserverbpp
        value: "{{ xrdp_xvnc_xserverbpp }}"
        state: present

    - name: Configure Globals MaxSessions
      community.general.ini_file:
        path: /etc/xrdp/sesman.ini
        section: Sessions
        option: MaxSessions
        value: "{{ xrdp_sesman_globals_max_sessions }}"
        state: present

    - name: Remove line 'test -x /etc/X11/Xsession && exec /etc/X11/Xsession'
            from /etc/xrdp/startwm.sh
      lineinfile:
        path: /etc/xrdp/startwm.sh
        regexp: "test -x /etc/X11/Xsession && exec /etc/X11/Xsession"
        state: absent

    - name: Remove line 'exec /bin/sh /etc/X11/Xsession'
            from /etc/xrdp/startwm.sh
      lineinfile:
        path: /etc/xrdp/startwm.sh
        regexp: "exec /bin/sh /etc/X11/Xsession"
        state: absent

    - name: Insert line 'i3' in /etc/xrdp/startwm.sh
      lineinfile:
        path: /etc/xrdp/startwm.sh
        line: "i3"
        state: present

    - name: Add xrdp user to ssl-certs group
      user:
        name: xrdp
        groups: ssl-cert
        append: yes

    - name: Start xrdp service
      sysvinit:
        name: xrdp
        state: started
        enabled: true

  become: true
  become_user: root
