---
- name: Install packages
  block:
  - name: Install tmux and dependencies
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - tmux
      - xclip

    become: true
    become_user: root

- name: Configure tmux
  template:
    src: templates/.tmux.conf.j2
    dest: "{{ local_user_home }}/.tmux.conf"
    mode: u+rw

- name: Install plugins
  git:
    repo: "https://github.com/tmux-plugins/{{ item.name }}.git"
    dest: "{{ local_user_home }}/.tmux/{{ item.name }}"
    version: "{{ item.version }}"
    force: true
  with_items:
    - "{{ tmux_plugins }}"
