---
- name: Install dependencies
  block:

  - name: Install python dependencies
    apt:
      name: "{{ item }}"
      update_cache: true
      state: present
    with_items:
      - "{{ python_required_packages }}"

  - name: Install neovim required dependencies
    apt:
      name: "{{ item }}"
      update_cache: true
      state: present
    with_items:
      - "{{ neovim_required_packages }}"

  become: true
  become_user: root
  tags:
    - install

- name: Include LazyGit installation tasks
  include_tasks: lazygit.yml
  tags:
    - lazygit

- name: Include Go Disk Usage installation tasks
  include_tasks: gdu.yml
  tags:
    - gdu

- name: Include bottom installation tasks
  include_tasks: bottom.yml
  tags:
    - bottom

- name: Include nvm installation tasks
  include_tasks: nvm.yml
  tags:
    - nvm

- name: Include clipboard installation tasks
  include_tasks: clipboard.yml
  tags:
    - clipboard

- name: Include tree-sitter installation tasks
  include_tasks: tree-sitter.yml
  tags:
    - tree-sitter

- name: Install AstroNvim
  block:

    - name: Clone AstroNvim repository
      git:
        repo: https://github.com/AstroNvim/template
        dest: ~/.config/nvim
        depth: 1

    - name: Remove template's git connection
      file:
        path: ~/.config/nvim/.git
        state: absent

  tags:
    - astro

