---
- name: Install dependencies
  block:

  - name: Install python dependencies
    apt:
      name: "{{ item }}"
      update_cache: true
      state: present
    with_items:
      - "{{ python_required_packages }}"

  - name: Install neovim required dependencies
    apt:
      name: "{{ item }}"
      update_cache: true
      state: present
    with_items:
      - "{{ neovim_required_packages }}"

  become: true
  become_user: root
  tags:
    - install

- name: Install neovim
  block:

    - name: Add neovim ppa
      apt_repository:
        repo: "{{ neovim_ppa }}"
        state: present

    - name: Install neovim from ppa
      apt:
        name: "{{ neovim_name }}"
        state: present

  become: true
  become_user: root
  tags:
    - install

- name: Install python neovim plugin
  pip:
    name: neovim
    executable: "{{ pip3_name }}"
    state: present
    extra_args: --user
  tags:
    - install

- name: Copy neovim config
  block:
    - name: Ensure that "{{ neovim_config_dir }}" exists
      file:
        path: "{{ neovim_config_dir }}"
        state: directory
        mode: u+rw

    - name: Copy neovim config
      copy:
        src: ./files/nvim/
        dest: "{{ neovim_config_dir }}"
        mode: u+rw
  tags:
    - install
    - config

- name: Install packer plugin for Neovim
  git:
    repo: https://github.com/wbthomason/packer.nvim
    dest: "{{ neovim_config_dir }}/packer.nvim"
    force: yes

