---

# Install python dependencies
- name: Install dependencies
  block:

  - name: Install python dependencies
    apt:
      name: "{{ item }}"
      update_cache: true
      state: present
    with_items:
      - "{{ python_required_packages }}"

  - name: Install neovim required dependencies
    apt:
      name: "{{ item }}"
      update_cache: true
      state: present
    with_items:
      - "{{ neovim_required_packages }}"

  become: true
  become_user: root
  tags:
    - install

# Install neovim
- name: Install neovim
  block:

    - name: Add neovim ppa
      apt_repository:
        repo: "{{ neovim_ppa }}"
        state: present

    - name: Install neovim from ppa
      apt:
        name: "{{ neovim_name }}"
        state: present

  become: true
  become_user: root

  tags:
    - install

- name: Install plugins
  block:

    - name: Install python neovim plugin
      pip:
        name: neovim
        executable: "{{ pip3_name }}"
        state: present
        extra_args: --user

  tags:
    - install

# Install vim-plug
- name: Install vim-plug
  block:
    - name: Create "{{ neovim_config_dir }}/autoload" directory
      file:
        path: "{{ neovim_config_dir }}/autoload"
        state: directory
        mode: u+rw

    - name: Install vim-plug
      get_url:
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest: "{{ neovim_config_dir }}/autoload/plug.vim"
        force: true
        mode: u+rw

  tags:
    - config

- name: Configure neovim
  block:
    - name: Ensure that "{{ neovim_config_dir }}/options" exists
      file:
        path: "{{ neovim_config_dir }}/options"
        state: directory
        mode: u+rw

    - name: Copy init.vim
      template:
        src: init.vim.j2
        dest: "{{ neovim_config_dir }}/init.vim"
        mode: u+rw

    - name: Apply options/*.vim
      template:
        src: "./options/{{ item }}.j2"
        dest: "{{ neovim_config_dir }}/options/{{ item }}"
        mode: u+rw
      with_items:
        - sets.vim
        - theme.vim
        - nvim-tree.vim
        - lualine.vim
        - telescope.vim

  tags:
    - config

- name: Install vim-plugins
  block:
    - name: Install vim plugins
      command: "nvim -E -s -u {{ neovim_config_dir }}/init.vim +PlugInstall +qall"
      changed_when: false

  tags:
    - bootstrap
    - configure
    - update
    - plugins
