---
- name: Install NVM and Node.js
  block:
    - name: Ensure curl is installed
      become: true
      apt:
        name: curl
        state: present

    - name: Install NVM
      become: false
      shell: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash
      args:
        executable: /bin/bash

    - name: Add NVM environment variable to profile
      become: false
      lineinfile:
        path: "{{ ansible_env.HOME }}/.profile"
        line: |
          export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
        create: yes

    - name: Load NVM
      become: false
      shell: . {{ ansible_env.HOME }}/.profile && . {{ ansible_env.HOME }}/.nvm/nvm.sh

    - name: Install Node.js version 20
      become: false
      shell: . {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm install 20

  tags:
    - nvm

