---
- name: Install tree-sitter-cli globally
  block:
    - name: Install tree-sitter-cli globally using npm
      npm:
        name: tree-sitter-cli
        global: yes
        state: present

  tags:
    - tree-sitter
